language: node_js
node_js:
  - '0.10'
deploy:
  provider: heroku
  app: express-tutorial 
  api_key:
    secure: FF7yK8m9adIZR9fmlyaVK1E+7EgROvZY9kznX+k2ik77EhQZ5y0l27c5jSPLmNcraeI3MXjVQ5kQLElGCRZvg/Y+dWg7XIOT5aRlvcrfxigkZJYnAYb8FFaGjkh7B+EmFhMO+D7wgx3oFqZnfUGtPN/TNpfhf3YTR9CTnxnMoj0=

